### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/swt/dnd/XXX$AjcClosureN (wrong name: XXX) can occur in conjunction with Equinox Aspect Caching

### ISSUE THREAD

**Issue by xpomul** [eclipse-aspectj/ajdt#45] opened 2023-09-07 12:30 UTC
# Summary

This is a complicated one involving the right timing and combination of RCPTT, AspectJ, Equinox Aspect Weaving, and Equinox Aspect Caching; please bear with me.

We have created an application that supports drag and drop from the outside, and we test this application with RCPTT.
Between each test case, we let RCPTT shut down and restart the application. This results in a quick succession of shutdowns and restarts. 

Every other week, we find that the tests in a test suite start failing from the second test case. In the log file, we can find this exception:

    java.lang.NoClassDefFoundError: org/eclipse/swt/dnd/FileTransfer$AjcClosure7 (wrong name: org/eclipse/swt/dnd/FileTransfer)

# Analysis

I managed to track down the issue over past weeks, and this is how things look to me:

RCPTT registers aspects for org.eclipse.swt.dnd.FileTransfer [here](https://github.com/xored/rcptt/blob/841461303fc27eb8840156793a3f0895460a39b6/runtime/tesla/org.eclipse.rcptt.tesla.swt.aspects/src/org/eclipse/rcptt/tesla/swt/aspects/ClipboardAspect.aj#L303).

In our application, `org.eclipse.swt.dnd.FileTransfer` is instantiated at some point during startup.
`org.eclipse.swt.dnd.FileTransfer` extends `org.eclipse.swt.dnd.ByteArrayTransfer`.

During loading, `org.eclipse.swt.dnd.FileTransfer` is loaded and woven by AspectJ.

Afterwards, in [o.a.w.tools.WeavingAdaptor:915](https://github.com/eclipse-aspectj/aspectj/blob/4accdcda5c990b19bb485aa3c22d61ec8afee921/weaver/src/main/java/org/aspectj/weaver/tools/WeavingAdaptor.java#L915), it is written into the _generatedClasses_ map - both under its own name and under the name of the main class (I didn't understand why exactly...). The latter entry is always overwritten for each generated class. 

Consequently, after this, _generatedClasses_ has the value (in the format key -> value):

    org.eclipse.swt.dnd.FileTransfer$AjcClosure1 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure1
    org.eclipse.swt.dnd.FileTransfer$AjcClosure3 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure3
    org.eclipse.swt.dnd.FileTransfer$AjcClosure5 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure5
    org.eclipse.swt.dnd.FileTransfer$AjcClosure7 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure7
    org.eclipse.swt.dnd.FileTransfer -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure7

However, these classes are not yet passed to the Equinox Aspect cache, for storing; instead, due to inheritance in the parent class `org.eclipse.swt.dnd.ByteArrayTransfer` is loaded first (basically in the native code of `ClassLoader.defineClass(org.eclipse.swt.dnd.FileTransfer)`) . 
This results in `org.eclipse.swt.dnd.ByteArrayTransfer` being also woven by AspectJ, and _generatedClasses_ is expanded. 
It now looks like this:

    org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure1 -> UnwovenClassFile with name 
    org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure1
    org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure3 -> UnwovenClassFile with name 
    org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure3
    org.eclipse.swt.dnd.ByteArrayTransfer -> UnwovenClassFile with name org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure3
    org.eclipse.swt.dnd.FileTransfer$AjcClosure1 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure1
    org.eclipse.swt.dnd.FileTransfer$AjcClosure3 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure3
    org.eclipse.swt.dnd.FileTransfer$AjcClosure5 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure5
    org.eclipse.swt.dnd.FileTransfer$AjcClosure7 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure7
    org.eclipse.swt.dnd.FileTransfer -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure7

Only then, on the way back up the stack, [o.e.e.w.adaptors.WeavingAdaptor.storeClass()](https://github.com/eclipse-equinox/equinox/blob/c91db89ef4ada8c48c912b01024f9f4f6622895b/bundles/org.eclipse.equinox.weaving.hook/src/org/eclipse/equinox/weaving/adaptors/WeavingAdaptor.java#L203) is executed, and [o.e.e.w.a.loadtime.OSGiWeavingAdaptor.getGeneratedClassesFor()](https://github.com/eclipse-aspectj/ajdt/blob/2f32ff979ea06237caf80e48280a4fe9bdeb4569/org.eclipse.equinox.weaving.aspectj/src/org/eclipse/equinox/weaving/aspectj/loadtime/OSGiWeavingAdaptor.java#L205) is called. 

From _generatedClasses_, the _result_ is formed by filtering out the class with the current name (`org.eclipse.swt.dnd.ByteArrayTransfer`). (Most likely, this was thought of as a fix for the fact that the generated classes are additionally registered under the name of the plain class as described above). But in this case, we have the problem that we have two of these original class names in the map: `org.eclipse.swt.dnd.ByteArrayTransfer` and `org.eclipse.swt.dnd.FileTransfer`.

The _result_ is, therefore, as follows:

```
org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure1 -> UnwovenClassFile with name org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure1
org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure3 -> UnwovenClassFile with name org.eclipse.swt.dnd.ByteArrayTransfer$AjcClosure3
org.eclipse.swt.dnd.FileTransfer$AjcClosure1 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure1
org.eclipse.swt.dnd.FileTransfer$AjcClosure3 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure3
org.eclipse.swt.dnd.FileTransfer$AjcClosure5 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure5
org.eclipse.swt.dnd.FileTransfer$AjcClosure7 -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure7
org.eclipse.swt.dnd.FileTransfer -> UnwovenClassFile with name org.eclipse.swt.dnd.FileTransfer$AjcClosure7
```

Consequently, the last entry is also passed to the AspectJ cache along with all others, and is written to the cache in [BundleCachingService.storeClassAndGeneratedClasses()](https://github.com/eclipse-equinox/equinox/blob/c91db89ef4ada8c48c912b01024f9f4f6622895b/bundles/org.eclipse.equinox.weaving.caching/src/org/eclipse/equinox/weaving/internal/caching/BundleCachingService.java#L273).

Now we have a file in the cache with the name `org.eclipse.swt.dnd.FileTransfer.class` but the contained byte array is actually the class bytes for `org.eclipse.swt.dnd.FileTransfer$AjcClosure7`. 

Under normal circumstances, nothing harmful happens, because we are still in the process of going up the stack, and in the next step, [o.e.e.w.adaptors.WeavingAdaptor.storeClass()](https://github.com/eclipse-equinox/equinox/blob/c91db89ef4ada8c48c912b01024f9f4f6622895b/bundles/org.eclipse.equinox.weaving.hook/src/org/eclipse/equinox/weaving/adaptors/WeavingAdaptor.java#L203) is called again for `org.eclipse.swt.dnd.FileTransfer`. 

Now, _generatedClasses_ is empty (it was already written to the cache and the _generatedClasses_ field was cleared after this), and only `org.eclipse.swt.dnd.FileTransfer` is written to the cache. Thus, the incorrect class file is overwritten by the correct `org.eclipse.swt.dnd.FileTransfer.class` and everything is fine.

The problem arises when the Equinox Aspect Caching's `CacheWriter` has built up a queue of several class files to write to the cache, and Eclipse is shut down now. In this case, the shutdown could happen at a point where the `CacheWriter` has just written the corrupt `org.eclipse.swt.dnd.FileTransfer.class` but not yet the correct, final one.

So we end up with a shut down Eclipse and the Weaving Cache containing `org.eclipse.swt.dnd.FileTransfer.class` (with the content of `org.eclipse.swt.dnd.FileTransfer$AjcClosure7`)

When Eclipse is started again, loading this class leads to the exception given above:

    java.lang.NoClassDefFoundError: org/eclipse/swt/dnd/FileTransfer$AjcClosure7 (wrong name: org/eclipse/swt/dnd/FileTransfer)

# Solution

The for loop in [o.e.e.w.a.loadtime.OSGiWeavingAdaptor.getGeneratedClassesFor()](https://github.com/eclipse-aspectj/ajdt/blob/2f32ff979ea06237caf80e48280a4fe9bdeb4569/org.eclipse.equinox.weaving.aspectj/src/org/eclipse/equinox/weaving/aspectj/loadtime/OSGiWeavingAdaptor.java#L205) should look like this:

```java
      for (Map.Entry<String, IUnwovenClassFile> entry : generated.entrySet())
      {
        final String name = entry.getKey();
        final IUnwovenClassFile unwovenClass = entry.getValue();
        if (!name.equals(className) && name.equals(unwovenClass.getClassName()))
        {
          result.put(name, unwovenClass.getBytes());
        }
      }
```

Here, we filter out any _UnwovenClassFile_ with a name that does not match the key in the map of generated classes.
(the `!name.equals(className)` condition might not even be required anymore if it only had the purpose to hande this exact case I have described above, but I was not entirely sure, so I kept it in as it does not harm).

**Comment by kriegaex** [comment] 2023-09-08 03:30
What you are describing is beyond my understanding, because I am merely trying to keep AJDT alive along with AspectJ. What you explained seems to make sense, and probably your analysis is correct. But still, I would feel way better if the PR would also include a test which fails before the fix and passes afterwards, reproducing the situation you just described. Would you mind creating one? If so, please also reorder (interactively rebase) the commits, so the failing test is committed first and the fix afterwards, making the test pass as a result. Thank you.

BTW, many tests are failing in this project, even though a while ago I repaired some or at least made the same ones fail on all OS platforms uniformly. I would, before eventually accepting the PR, run the tests before and after your fix and heuristically compare if anything else broke as a side effect of your improvement. It is just the tiny bit of due diligence I can apply before merging something I am not 100% sure is correct. But by all means, I am welcoming your contribution and want to incorporate it into AJDT as soon as reasonably possible.

**Comment by xpomul** [comment] 2023-09-15 15:27
@kriegaex thanks having a look, even though the project is more or less in maintenance mode.
And sorry for taking some time, but I first had to allocate again some time to get back to this.
Anyways, I have created a test case now and reordered the commits. Since there was not yet a test plugin/project for org.eclipse.equinox.weaving.aspectj, I have created a new one -- I hope the setup is fine. 

In the test I have tried to find a sweet spot between test complexity and effectiveness. Setting up everything with full weaving and provoking the problem have been too complicated in my opinion, so I have tried to set up the state that leads to the problem using reflection and subclassing (I didn't want to add a Mockito dependency...).

In the end, the test result shows the problem in that it returns a non-generated class as part of the `getGeneratedClassesFor` method call. With the second commit applied, the test case execution is successful.

**Comment by kriegaex** [comment] 2023-10-24 03:24
I want to apologise for not looking at this issue for so long. I am quite busy these days. Now, I have run your test without the actual code change to reproduce the problem and then with the change to fix it. Thank you so much, the PR has been merged.

**Closed by kriegaex** 2023-10-24 03:24 UTC
Labels: bug

**Comment by kriegaex** [comment] 2023-10-24 03:33
Signed AJDT builds for 4.23 (2022-03) and 4.26+ (2022-12+) are available on the usual update sites.

**Comment by xpomul** [comment] 2023-10-24 12:32
> I want to apologise for not looking at this issue for so long. I am quite busy these days. Now, I have run your test without the actual code change to reproduce the problem and then with the change to fix it. Thank you so much, the PR has been merged.

No worries. Thank you for your feedback and assistance, and thanks for merging :-)
