### ISSUE TITLE
Cannot create JUnit 5 run configuration for test containing lambda expression

### ISSUE THREAD

**Issue by avenue68** [eclipse-aspectj/ajdt#1] opened 2021-12-10 02:00 UTC
#### Summary
When I try to run a Junit5 test class in Eclipse AspectJ Project, I got the following error message on the following pop-up.
```
Launching of JUnit tests unexpectedly failed. Check log for details.
Reason: <anonymous eclipse/org.aspectj#1> {key=Lorg/assertj/core/api/ThrowableAssert$ThrowingCallable;}[in testMethod() [in AppTest [in [Working copy] AppTest.java [in MY PROJECT...]]]] does not exist.
```
(Sorry this is in Japanese. the same content as above.)
![error](https://user-images.githubusercontent.com/83228978/145398871-0bb2e03b-61fa-4005-b239-e1ff2fdf7b47.png)

Here are some information I confirmed.
- The error happens when calling AssertJ's assertion methods which needs ThrowableAssert$ThrowingCallable dependency like isThrownBy() method.
- Even if I don't define any Aspect class nor use AspectJ dependencies in pom.xml, the error happens in Eclipse AspectJ project.
- After re-converting to a normal maven project, the error don't happen.
- All dependencies are the latest stable version.
- The problem don't occur when run the test codes by [clicking following icons → clicking one of executions in history] and then test run properly (including aspects).
![icon](https://user-images.githubusercontent.com/83228978/145411593-c54f48d5-cd9a-4988-a58e-5a64d29aa67c.PNG)

#### Example
The test method which will result in the error.
```java
package com.example;

import static org.assertj.core.api.Assertions.*;
import org.junit.jupiter.api.Test;

public class AppTest 
{
    @Test
    public void testMethod()
    {
    	assertThatNoException().isThrownBy(() -> System.out.println("aaaaa"));
    }
}
```

Eclipse's log
```
!ENTRY org.eclipse.jdt.junit 4 4 2021-12-09 21:29:25.147
!MESSAGE ERROR
!STACK 1
Java Model Exception: Error in Java Model (code 969): <anonymous eclipse/org.aspectj#1> {key=Lorg/assertj/core/api/ThrowableAssert$ThrowingCallable;} [in shouldAnswerWithTrue() [in AppTest [in [Working copy] AppTest.java [in MY PROJECT...]]]] does not exist.
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:574)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:617)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:328)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:314)
	at org.eclipse.jdt.internal.core.Member.getFlags(Member.java:172)
	at org.eclipse.jdt.internal.junit.util.CoreTestSearchEngine.isAccessibleClass(CoreTestSearchEngine.java:64)
	at org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.internalIsTest(JUnit5TestFinder.java:259)
	at org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.findTestsInContainer(JUnit5TestFinder.java:226)
	at org.eclipse.jdt.internal.junit.util.TestSearchEngine.lambda$0(TestSearchEngine.java:42)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2021-12-09 21:29:25.148
!MESSAGE <anonymous eclipse/org.aspectj#1> {key=Lorg/assertj/core/api/ThrowableAssert$ThrowingCallable;} [in shouldAnswerWithTrue() [in AppTest [in [Working copy] AppTest.java [in MY PROJECT...]]]] does not exist.
```

**Comment by kriegaex** [comment] 2024-01-07 02:10
> It's likely that this class is not properly converting lambdas to `IJavaElement`s. It is converting them to class declarations instead of lambdas.
> 
> _Note by kriegaex: Updating stale link by working equivalent as follows._
> 
> https://github.com/eclipse-aspectj/ajdt/blob/9d363de39a7aba80c3f7658f4fef78d8e7620f97/org.aspectj.ajde/source/org/aspectj/org/eclipse/jdt/internal/core/CompilationUnitStructureRequestor.java

This class is from AspectJ (actually from JDT Core, relocated into the AspectJ namespace) and used to be redundantly committed to the AJDT repository, which is not longer the case, after a while ago I weeded out these redundancies in favour of manually unpacking AspectJ code into the corresponding target directories during the build.

The original `CompilationUnitStructureRequestor` class is [here in AspectJ's JDT Core fork](https://github.com/eclipse-aspectj/eclipse.jdt.core/blob/aspectj/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnitStructureRequestor.java). In AJDT we have a corresponding [`AJCompilationUnitStructureRequestor`](https://github.com/eclipse-aspectj/ajdt/blob/master/org.eclipse.ajdt.core/src/org/eclipse/ajdt/core/parserbridge/AJCompilationUnitStructureRequestor.java) extending it.

I have verified, that AspectJ uses the JDT Core class unchanged from upstream Eclipse JDT Core. I.e., if anything is not working in AJDT, is probably needs to be fixed in the subclass.

**Comment by kriegaex** [comment] 2024-01-07 02:56
@avenue68, to my own surprise, I cannot reproduce it anymore with the current AJDT version on 2023-12. I have an idea what might have fixed it, but this is pure speculation. First, I would like to know if you can reproduce it according to the setup for Eclipse 2023-12 (4.30) according to [this guide](https://github.com/eclipse-aspectj/aspectj/blob/master/docs/developer/IDE.md#eclipse). Please re-test and let me know the result, before I decide to either close the issue or try t reproduce again and investigate more.

**Comment by kriegaex** [comment] 2024-01-13 04:57
No reply → closing. Feel free to reply t either confirm that the problem is gone or to reopen.

**Closed by kriegaex** 2024-01-13 04:57 UTC

**Comment by avenue68** [comment] 2024-01-15 07:07
@kriegaex 
I couldn't reproduce the problem so it seems gone. Sorry for the late reply.
